baseurl      = "http://madskjeldgaard.dk"
title        = "Mads Kjeldgaard"
languageCode = "en-uk"
theme        = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Subtitle for home
  homeSubtitle = "Composer and developer"

  #homeVimeo="458966794"
  homeBG="/img/small/mads-kjeldgaard-press-photo-2020-photo-cred-Sofie-Amalie-Klougart_9.jpg"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Website of composer Mads Kjeldgaard"
  keywords = "homepage, blog, supercollider, computermusic, creative coding"
  images = ["/img/small/mads-kjeldgaard-press-photo-2020-photo-cred-Sofie-Amalie-Klougart_9.jpg"]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

[taxonomies]
	category = "categories"
	tag      = "tags"
	series   = "series"

[languages]
  [languages.en]
    title = "Mads Kjeldgaard"
    subtitle = "Composer and developer"
    keywords = "computer music, supercollider, rust, vim, linux"
    copyright = ''
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "madskjeldgaard"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
	  [[menu.main]]
    identifier = "posts"
    name       = "posts"
    url        = "/posts"

	[[menu.main]]
    identifier = "sound"
    name       = "sound"
    url        = "/pages/work"

	[[menu.main]]
    identifier = "software"
    name       = "software"
    url        = "/pages/software"

	[[menu.main]]
	identifier = "about"
    name       = "about"
    url        = "/pages/about"
	[[menu.main]]
	identifier = "contact"
    name       = "contact"
    url        = "/pages/contact"
